---
- name: check dotfiles
  stat:
    path: "{{ ansible_env.HOME }}/.dotfiles"
  register: dotfiles

- name: install dotfiles
  git:
    repo: "{{ kse201_dotfiles.repo.url }}"
    dest: "{{ ansible_env.HOME }}/.dotfiles"
    depth: "{{ kse201_dotfiles.repo.depth }}"
    version: "{{ kse201_dotfiles.repo.version }}"
  when: not dotfiles.stat.exists
