---
- name: check dotfiles
  stat:
    path: "{{ clone_path }}"
  register: dotfiles

- name: install dotfiles
  git:
    repo: "https://{{ rep.host }}/{{ repo.name }}"
    dest: "{{ clone_path }}"
    depth: "{{ repo.depth }}"
    version: "{{ repo.version }}"
  when: not dotfiles.stat.exists
