---
- block:
  - name: ensure basic packages is installed
    pacman:
      name: "{{ item }}"
    with_items:
      - "{{ kse201_base.packages.native.basic }}"

  - name: ensure proxychains-ng is installed if HTTP_PROXY is set
    pacman:
      name: proxychains-ng
    when: not "{{ ansible_env.HTTP_PROXY }}" == ''

  - name: ensure proxychains-ng is installed if HTTP_PROXY is set
    template:
      src: proxychains.conf.j2
      dest: '/etc/proxychains.conf'
    when: not "{{ ansible_env.HTTP_PROXY }}" == ''

  - name: deploy freshclam.conf
    template:
      src: ../templates/freshclam.conf.j2
      dest: /etc/clamav/freshclam.conf
      mode: 0700
      owner: root

  - name: ensure additional packages is installed
    pacman:
      name: "{{ item }}"
    with_items:
      - "{{ kse201_base.packages.native.additional }}"

  - name: ensure ruby is installed
    pacman:
      name: ruby
    tags:
      - ruby

  - name: ensure python is installed
    pacman:
      name: "{{ item }}"
    with_items:
      - python
      - python-pip
    tags:
      - python

  - name: ensure docker is installed
    pacman:
      name: docker
    tags:
      - docker
  become: yes
