---
- block:
  - include: fish.yml

  - name: ensure basic packages is installed (in Archlinux)
    pacman:
      name: "{{ kse201_base.packages.native.basic }}"
    when: ansible_os_family == "Archlinux"

  - name: ensure basic packages is installed (in RedHat family)
    yum:
      name: "{{ kse201_base.packages.native.basic }}"
    when: ansible_os_family == "RedHat"

  - include: proxy.yml
    when: ansible_env['HTTP_PROXY'] is defined

  - name: make freshclam config dir
    file:
      path: /etc/clamav
      state: directory

  - name: deploy freshclam.conf
    template:
      src: ../templates/freshclam.conf.j2
      dest: /etc/clamav/freshclam.conf
      mode: 0700
      owner: root
    vars:
      http_proxy:
        host: "{{ ansible_env.HTTP_PROXY | urlsplit('hostname')}}"
        port: "{{ ansible_env.HTTP_PROXY | urlsplit('port')}}"
        pass: "{{ ansible_env.HTTP_PROXY | urlsplit('password')}}"
        user: "{{ ansible_env.HTTP_PROXY | urlsplit('username')}}"
    when: ansible_env['HTTP_PROXY'] is defined

  - name: ensure additional packages is installed
    pacman:
      name: "{{ kse201_base.packages.native.additional }}"
    when: ansible_os_family == "Archlinux"

  become: yes
