---
- name: install packages
  pacman:
    name: "{{ item }}"
  with_items:
    - "{{ kse201_base.packages.pacman }}"

- name: ensure ruby is installed
  pacman:
    name: ruby
  tags:
    - ruby

- name: ensure python is installed
  pacman:
    name: "{{ item }}"
  with_items:
    - python
    - python-pip
  tags:
    - python

- name: ensure docker is installed
  pacman:
    name: docker
  tags:
    - docker
