---
- name: ensure pyenv is installed
  pacman:
    name: ['python', 'python2']
  tags:
    - python
  when: ansible_os_family == "Archlinux"
  become: yes

- name: ensure python is installed
  yum:
    name: ['python', 'python-pip']
  tags:
    - python
  when: ansible_os_family == "RedHat"
  become: yes

- name: install pip
  pip:
    name: "{{ kse201_base.python.pips }}"
    extra_args: --user
  ignore_errors: yes # TODO: failed install with vim-vint
