---
- name: link dotfiles
  file:
    src: "{{ clone_path }}/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    state: link
  with_items:
    - "{{ home_files }}"

- name: link vim config
  file:
    src: "{{ clone_path }}/nvim/{{ item.neovim }}"
    dest: "{{ ansible_env.HOME }}/{{ item.vim }}"
    state: link
  with_items:
    - {vim: .vimrc, neovim: init.vim}
    - {vim: .gvimrc, neovim: gvim.vim}
    - {vim: .vimrc.plugin, neovim: plugin.vim}

- name: make xdg config dir
  file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory

- name: link xdg config files
  file:
    src: "{{ clone_path }}/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/{{ item }}"
    state: link
  with_items:
    - "{{ xdg_config_files }}"
