require 'rake'
require 'rspec/core/rake_task'
require 'yaml'

task default: :spec

desc 'clean vagrant'
task :clean do
  `vagrant destroy -f`
end

desc 'Run serverspec tests'
RSpec::Core::RakeTask.new(:spec) do |t|
  ENV['TARGET_HOST'] = 'default'
  t.pattern = 'spec/*_spec.rb'
end
